# Generated by Django 5.0.2 on 2024-03-07 19:08

import django.db.models.deletion
import file_manager.models
import file_manager.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=file_manager.models.user_upload_path)),
                ('minify', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, help_text='UPLOADED FILE METADATA', null=True, validators=[file_manager.validators.JSONSchemaValidator(limit_value={'properties': {'file_type': {'type': 'string'}, 'name': {'type': 'string'}, 'size': {'type': 'number'}}, 'required': ['name', 'size', 'file_type'], 'type': 'object'})])),
                ('minification_log', models.JSONField(blank=True, help_text='UPLOADED FILE MINIFICATION LOG DATA', null=True, validators=[file_manager.validators.JSONSchemaValidator(limit_value={'properties': {'memory_usage': {'type': 'number'}, 'time_taken': {'type': 'number'}}, 'required': ['memory_usage', 'time_taken'], 'type': 'object'})])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
