"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

import mongoengine
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ENV
env = environ.Env(
    DEBUG=(bool, False),
    USER_DB_NAME=(str, "postgres"),
    USER_DB_HOST=(str, "localhost"),
    USER_DB_PORT=(str, "5432"),
    USER_DB_USER=(str, "postgres"),
    USER_DB_PASSWORD=(str, "postgres"),
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

AUTH_USER_MODEL = 'accounts.User'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'accounts',
    'file_manager',
    'logger',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # CUSTOM GRAYLOG LOGING MIDDLEWARE
    'logger.middleware.GraylogExceptionMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('USERS_DB_NAME'),
        'HOST': env('USERS_DB_HOST'),
        'PORT': env('USERS_DB_PORT'),
        'USER': env('USERS_DB_USER'),
        'PASSWORD': env('USERS_DB_PASSWORD')
    }
}

# MONGODB CONNECTION

_MONGODB_NAME = env("MONGO_DB_NAME")
_MONGODB_DATABASE_HOST = env("MONGO_DB_HOST")
_MONGODB_DATABASE_USER = env("MONGO_ROOT_USER")
_MONGODB_DATABASE_PASS = env("MONGO_ROOT_PASS")

mongoengine.connect(
    _MONGODB_NAME,
    host=_MONGODB_DATABASE_HOST,
    username=_MONGODB_DATABASE_USER,
    password=_MONGODB_DATABASE_PASS,
    authentication_source='admin',
    connect=False
)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Configs

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(env('ACCESS_TOKEN_LIFETIME'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(env('REFRESH_TOKEN_LIFETIME'))),
    'UPDATE_LAST_LOGIN': True,
}

# GRAYLOG LOGGING CONFIGS
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'graypy': {
            'class': 'graypy.GELFTCPHandler',
            'host': env('GRAYLOG_HOSTNAME'),
            'port': int(env('GRAYLOG_GELF_PORT')),
        },
    },
    'loggers': {
        'request_errors': {
            'handlers': ['graypy'],
            'level': 'ERROR',
            'propagate': True,
        },
        'warnings': {
            'handlers': ['graypy'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
